### ISSUE TITLE
Styling fixes and standardization

### ISSUE THREAD

**Issue by andiedoescode** [the-collab-lab/tcl-68-smart-shopping-list#64]
- [x] Check and standardize across views and components as needed:
  - [x] Page margins
  - [x] Text color
  - [x] Form input height, background color, font size
  - [x] Button radius
- [x] Fix home page styling
  - [x] Space next to logout
  - [x] New list input location
  - [x] Side margins

Current deployment:
![image](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/98671035/6059cc42-6b6c-489c-9e12-970f1f5d60d2)

**Comment by DevinaG007** [comment]
Hey, thanks for fixing the funky and missed styling! You may have already noticed this (based on the item "text color") but just in case, wanted to point out that some of the text on this page is invisible because it's white (I think potentially it defaults to white in dark mode if no text color is assigned.) 

I'm sorry for not being able to help out more this week. Best of luck!

![Screenshot_20240407_115043_Chrome.jpg](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/137969744/394c7a79-a7a4-49ea-81f9-0a7ed5caf430)

**Comment by andiedoescode** [comment]
@DevinaG007 Thanks for the catch! I did a double-check after seeing this and patched up a couple of missing spots.
